name: App_Deployment

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

env:
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/angularapp:${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build Docker Image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGON_SERVER }}
        username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
        password: ${{ secrets.SERVICE_PRINCIPAL_TOKEN }}
    - run: docker build . -t ${{ env.IMAGE_NAME }}

    - name: 'Security Scan for Docker Image'
      uses: Azure/container-scan@v0
      with:
        image-name: ${{ env.IMAGE_NAME }}
        severity-threshold: 'MEDIUM'
      env:
        DOCKLE_HOST: "unix:///var/run/docker.sock"

    - name: 'Push Docker Image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGON_SERVER }}
        username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
        password: ${{ secrets.SERVICE_PRINCIPAL_TOKEN }}
    - run: docker push ${{ env.IMAGE_NAME }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ env.IMAGE_NAME }}
        registry-login-server: ${{ env.ACR_LOGON_SERVER }}
        registry-username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
        registry-password: ${{ secrets.SERVICE_PRINCIPAL_TOKEN }}
        name: angular-app
        location: 'east us'
