# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/angularapp:${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
    - uses: actions/checkout@v3
    - name: Build Application - Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo Image name ${{ env.IMAGE_NAME }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: 'Build Docker Image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGON_SERVER }}
        username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
        password: ${{ secrets.SERVICE_PRINCIPAL_TOKEN }}
    - run: docker build . -t ${{ env.IMAGE_NAME }}